<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>X-Barcode Vitamin B1</title>
    <link type="text/css" rel="stylesheet" href="/sm-xbarcode-app/css/font-awesome.min.css">
    <link type="text/css" rel="stylesheet" href="/sm-xbarcode-app/css/base.css"  />
    <link type="text/css" rel="stylesheet" href="/sm-xbarcode-app/css/app.css"  />
    <link type="text/css" rel="stylesheet" href="/sm-xbarcode-app/css/print.css"  media="print"/>
    <script src="/sm-xbarcode-app/js/jquery-2.1.4.min.js"></script>
</head>
<body>
    <section id="xbarcodeapp"></section>
    <script src="/sm-xbarcode-app/js/bundle.js"></script>
</body>
</html>
